In [25]:
#Applying Bayes Theorem
def bayes_theorem(prior, likelihood, marginal_likelihood):
    posterior = (likelihood * prior) / marginal_likelihood
    return posterior
    
#assumed values
prior = 0.01  
likelihood = 0.99  
false_positive_rate = 0.05 
false_negative_rate = 1 - likelihood 

marginal_likelihood = (likelihood * prior) + (false_positive_rate * (1 - prior))

posterior = bayes_theorem(prior, likelihood, marginal_likelihood)

print("The posterior probability of having the disease given a positive test is: " + str(round(posterior*100, 4)))


The posterior probability of having the disease given a positive test is: 16.6667


In [10]:
#finding eigen values and eigen vectors
import numpy as np

# assume a matrix 
A = np.array([[4, 1, 2],
              [0, 3, -1],
              [0, 0, 2]])

# Calculating eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors

(array([4., 3., 2.]),
 array([[ 1.        , -0.70710678, -0.72760688],
        [ 0.        ,  0.70710678,  0.48507125],
        [ 0.        ,  0.        ,  0.48507125]]))

In [18]:
#calculating determinant of a 3x3 matrix and finding its inverse if possible
# assume a matrix
B = np.array([[2, 3, 1],
              [4, 5, 6],
              [7, 8, 9]])

# Calculating the determinant
det = np.linalg.det(B)
print("Determinant:", det)

# Calculating the inverse if the determinant is non-zero
if det != 0:
    inv = np.linalg.inv(B)
    print("Inverse:", inv)

Determinant: 9.000000000000005
Inverse: [[-0.33333333 -2.11111111  1.44444444]
 [ 0.66666667  1.22222222 -0.88888889]
 [-0.33333333  0.55555556 -0.22222222]]


In [24]:
# Normal distribution and calculating probabilities 
import scipy.stats as stats

mean = 0
stddev = 1

normal_dist = stats.norm(mean, stddev)

#Calculating the probability that a value is less than 1 (P(X < 1))
prob_less_than_1 = normal_dist.cdf(1)
print("P(X < 1):", prob_less_than_1)


P(X < 1): 0.8413447460685429
